import React from "react";
import { Table } from "antd";
import { AIDetails } from "@/types";
import AIDetailsComponent from "../AIDetails/AI";
import style from "./style.module.scss";
import ColumnHeaderTable from "../ColumnHeaderTable/ColumnHeaderTable";

type TweetTableProps = {
    data: Array<{
        key: number;
        tokenName: string;
        tweetDate: string;
        tweet: string;
        username: string;
        aiDetails: AIDetails;
    }>;
};



const columns = [
    {
        title: <ColumnHeaderTable title="Token Name" tooltipText="The name of the coin" />,
        dataIndex: "tokenName",
        key: "tokenName",
    },
    {
        title: <ColumnHeaderTable title="Tweet Date" tooltipText="The exact date of the tweet" />,
        dataIndex: "tweetDate",
        key: "tweetDate",
    },
    {
        title: <ColumnHeaderTable title="Tweet" tooltipText="The content of the tweet itself." />,
        dataIndex: "tweet",
        key: "tweet",
    },
    {
        title: <ColumnHeaderTable title="Username" tooltipText="The username of the person that posted the tweet." />,
        dataIndex: "username",
        key: "username",
    },
    {
        title: <ColumnHeaderTable title="AI Details" tooltipText="The insights and analyses generated by the AI model." />,
        dataIndex: "aiDetails",
        key: "aiDetails",
        render: (aiDetails: AIDetails) => <AIDetailsComponent aiDetails={aiDetails} />,
    },
];

const TweetTable: React.FC<TweetTableProps> = ({ data }) => {
    return (
        <div className={style.antdTable}>
            <Table
                dataSource={data}
                columns={columns}
                pagination={false}
            />
        </div>
    );
};

export default TweetTable;
